#define MASTER_RIGHT

#define MULTIPLE_KEYS_PER_THUMB
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE -80

#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
