#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_DELAY 200
#define AUTO_MOUSE_DEBOUNCE 25
#define TASK_SWITCHING
#define MULTIPLE_KEYS_PER_THUMB
#define RGB_MATRIX_DISABLE_SHARED_KEYCODES
